version: '3'

services:
  db:
    image: mariadb:10.11.2-jammy
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my_db_root_password
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=my_db_user
      - MYSQL_PASSWORD=my_password
    expose:
      - 3306
      - 33060
    networks:
      - nginx_default
      - default

  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=my_db_user
      - WORDPRESS_DB_PASSWORD=my_password
      - WORDPRESS_DB_NAME=my_db
    networks:
      - nginx_default
      - default

volumes:
  db_data:
  wp_data:

networks:
  nginx_default:
    name: nginx_default
  default:
    driver: bridge
